### ISSUE TITLE
Invalid ApplicationSecret 'None'

### ISSUE THREAD

**Issue by SirCmpwn** [Inikup/OVH-WebKVM#2]
```
Traceback (most recent call last):
  File "./kvm.py", line 47, in <module>
    servers = client.get('/dedicated/server')
  File "/home/sircmpwn/sources/OVH-WebKVM/lib/python3.6/site-packages/ovh/client.py", line 345, in get
    return self.call('GET', _target, None, _need_auth)
  File "/home/sircmpwn/sources/OVH-WebKVM/lib/python3.6/site-packages/ovh/client.py", line 411, in call
    result = self.raw_call(method=method, path=path, data=data, need_auth=need_auth)
  File "/home/sircmpwn/sources/OVH-WebKVM/lib/python3.6/site-packages/ovh/client.py", line 488, in raw_call
    self._application_secret)
ovh.exceptions.InvalidKey: Invalid ApplicationSecret 'None'
```

Perhaps the ovh module interface changed?

**Comment by SirCmpwn** [comment]
Installing ovh==0.4.2 (as opposed to >=0.4.2) does not fix the issue.

**Comment by SirCmpwn** [comment]
Ah, have to change `[ovh-eu]` to `[ovh-ca]` in the config.

**Comment by jleroy** [comment]
Thank you for your report.
I've updated the `ovh.conf` accordingly in bfcb2d16a8350953535ddd98901df51961713b8c.
